brasileirao = ("Botafogo", "Palmeiras", "Fortaleza", "Internacional", "Flamengo", "São Paulo", "Cruzeiro", "Bahia", "Corinthians", "Vitória", "Vasco", "Juventude", "Grêmio","Fluminense", "Atlético-MG","RB Bragantino","Ceará","Santos","Sport","Mirassol")
print("Lista de times do Brasileirão:")
print(", ".join(brasileirao))
print("\nOs 5 primeiros colocados:")
print(", ".join(brasileirao[:5]))
print("\nOs 4 últimos colocados:")
print(", ".join(brasileirao[-4:]))
print("\nTimes em ordem alfabética:")
print(", ".join(sorted(brasileirao)))